_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 41
                - 55
                - 80
            "2":
                - 1
                - 41
                - 55
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
