wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729066828
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 80
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.8
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
